from app import app
from datetime import date
from models import db, User, Date, Cat, UserCat

with app.app_context():

    print("Deleting data ... ")
    User.query.delete()
    Date.query.delete()
    UserCat.query.delete()
    Cat.query.delete()

    print("Creating Users ... ")
    u1 = User(username = 'min', email = 'min@gmail.com', password = 'password')
    u2 = User(username = 'jane', email = 'jane@gmail.com', password = 'password')
  

    users = [u1, u2]
    db.session.add_all(users)
    db.session.commit()

    print("Creating Dates ... ")
    # d1 = Date(day = date(2023, 4, 23), steps = 2000, user_id = u1.id)
    # d2 = Date(day = date(2023, 4, 23), steps = 3000, user_id = u2.id)
    # d3 = Date(day = date(2023, 4, 23), steps = 4000, user_id = u3.id)
    # d4 = Date(day = date(2023, 4, 24), steps = 5000, user_id = u1.id)
    # d5 = Date(day = date(2023, 4, 24), steps = 6000, user_id = u2.id)
    # d6 = Date(day = date(2023, 4, 24), steps = 7000, user_id = u3.id)

    d1 = Date(day = "2023-4-23", steps = 20000, user_id = u1.id)
    d2 = Date(day = "2023-4-23", steps = 500000, user_id = u2.id)

    dates = [d1, d2]
    db.session.add_all(dates)
    db.session.commit()


    print('Creating Cats ... ')
    c1 = Cat(name = 'Lucy', image = './Cats/black10.png', description = 'black cat', )
    c2 = Cat(name = 'Willow', image = './Cats/black20.png', description = 'black cat with green eyes', )
    c3 = Cat(name = 'Ash', image = './Cats/black30.png', description = 'calico cat', )
    c4 = Cat(name = 'Loki', image = './Cats/black40.png', description = '')
    c5 = Cat(name = 'Rose', image = './Cats/black50.png', description = '')
    c6 = Cat(name = 'Bella', image = './Cats/blue1.png', description = '')
    c7 = Cat(name = 'Leo', image = './Cats/blue2.png', description = '')
    c8 = Cat(name = 'Jasper', image = './Cats/blue3.png', description = '')
    c9 = Cat(name = 'Nala', image = './Cats/blue4.png', description = '')
    c10 = Cat(name = 'Mocha', image = './Cats/brown1.png', description = '')
    c11 = Cat(name = 'Gracie', image = './Cats/brown2.png', description = '')
    c12 = Cat(name = 'Nugget', image = './Cats/brown3.png', description = '')
    c13 = Cat(name = 'Cookie', image = './Cats/brown4.png', description = '')
    c14 = Cat(name = 'Hazel', image = './Cats/brown5.png', description = '')
    c15 = Cat(name = 'Iris', image = './Cats/brown6.png', description = '')
    c16 = Cat(name = 'Bear', image = './Cats/brown7.png', description = '')
    c17 = Cat(name = 'Polly', image = './Cats/brown8.png', description = '')
    c18 = Cat(name = 'Tofu', image = './Cats/brown9.png', description = '')
    c19 = Cat(name = 'Belle', image = './Cats/calico.png', description = '')
    c20 = Cat(name = 'Kiki', image = './Cats/cottoncandy_blue.png', description = '')
    c21 = Cat(name = 'Lala', image = './Cats/cottoncandy_pink.png', description = '')
    c22 = Cat(name = 'Cheese', image = './Cats/cream1.png', description = '')
    c23 = Cat(name = 'Boots', image = './Cats/cream2.png', description = '')
    c24 = Cat(name = 'Salem', image = './Cats/dark.png', description = '')
    c25 = Cat(name = 'Clover', image = './Cats/gamboy1.png', description = '')
    c26 = Cat(name = 'Boo', image = './Cats/gamboy2.png', description = '')
    c27 = Cat(name = 'Luigi', image = './Cats/gamboy3.png', description = '')
    c28 = Cat(name = 'Casper', image = './Cats/ghost.png', description = '')
    c29 = Cat(name = 'Midas', image = './Cats/gold.png', description = '')
    c30 = Cat(name = 'Amber', image = './Cats/gray1.png', description = '')
    c31 = Cat(name = 'Bobbi', image = './Cats/gray2.png', description = '')
    c32 = Cat(name = 'Congee', image = './Cats/gray3.png', description = '')
    c33 = Cat(name = 'Skins', image = './Cats/hairless1.png', description = '')
    c34 = Cat(name = 'Pip', image = './Cats/hairless2.png', description = '')
    c35 = Cat(name = 'Luna', image = './Cats/indigo.png', description = '')
    c36 = Cat(name = 'Simba', image = './Cats/orange1.png', description = '')
    c37 = Cat(name = 'Nick', image = './Cats/orange2.png', description = '')
    c38 = Cat(name = 'Dip', image = './Cats/orange3.png', description = '')
    c39 = Cat(name = 'Peanut', image = './Cats/orange4.png', description = '')
    c40 = Cat(name = 'Peach', image = './Cats/peach.png', description = '')
    c41 = Cat(name = "Bonibel", image = './Cats/peach.png', description = '')
    c42 = Cat(name = 'Atom', image = './Cats/radioactive.png', description = '')
    c43 = Cat(name = 'Meimei', image = './Cats/red1.png', description = '')
    c44 = Cat(name = 'Olive', image = './Cats/red2.png', description = '')
    c45 = Cat(name = 'Dijon', image = './Cats/sealpoint.png', description = '')
    c46 = Cat(name = 'Stitch', image = './Cats/teal.png', description = '')
    c47 = Cat(name = 'Coconut', image = './Cats/white.png', description = '')
    c48 = Cat(name = 'Chloe', image = './Cats/whitegray1.png', description = '')
    c49 = Cat(name = 'Lucifer', image = './Cats/whitegray1.png', description = '')
    c50 = Cat(name = 'Namu', image = './Cats/.png', description = '')

    cats = [c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31, c32, c33, c34, c35, c36, c37, c38, c39, c40, c41, c42, c43, c44, c45, c46, c47, c48, c49, c50]
    db.session.add_all(cats)
    db.session.commit()


    print('Creating Cat Owners ... ')
    uc1 = UserCat(user_id = u2.id, cat_id = c1.id)
    uc2 = UserCat(user_id = u2.id, cat_id = c2.id)
    uc3 = UserCat(user_id = u2.id, cat_id = c3.id)
    uc4 = UserCat(user_id = u2.id, cat_id = c4.id)
    uc5 = UserCat(user_id = u2.id, cat_id = c5.id)
    uc6 = UserCat(user_id = u2.id, cat_id = c6.id)
    uc7 = UserCat(user_id = u2.id, cat_id = c7.id)
    uc8 = UserCat(user_id = u2.id, cat_id = c8.id)
    uc9 = UserCat(user_id = u2.id, cat_id = c9.id)
    uc10 = UserCat(user_id = u2.id, cat_id = c10.id)
    uc11 = UserCat(user_id = u2.id, cat_id = c11.id)
    uc12 = UserCat(user_id = u2.id, cat_id = c12.id)
    uc13 = UserCat(user_id = u2.id, cat_id = c13.id)
    uc14 = UserCat(user_id = u2.id, cat_id = c14.id)
    uc15 = UserCat(user_id = u2.id, cat_id = c15.id)
    uc16 = UserCat(user_id = u2.id, cat_id = c16.id)
    uc17 = UserCat(user_id = u2.id, cat_id = c17.id)
    uc18 = UserCat(user_id = u2.id, cat_id = c18.id)
    uc19 = UserCat(user_id = u2.id, cat_id = c19.id)
    uc20 = UserCat(user_id = u2.id, cat_id = c20.id)
    uc21 = UserCat(user_id = u2.id, cat_id = c21.id)
    uc22 = UserCat(user_id = u2.id, cat_id = c22.id)
    uc23 = UserCat(user_id = u2.id, cat_id = c23.id)
    uc24 = UserCat(user_id = u2.id, cat_id = c24.id)
    uc25 = UserCat(user_id = u2.id, cat_id = c25.id)
    uc26 = UserCat(user_id = u2.id, cat_id = c26.id)
    uc27 = UserCat(user_id = u2.id, cat_id = c27.id)
    uc28 = UserCat(user_id = u2.id, cat_id = c28.id)
    uc29 = UserCat(user_id = u2.id, cat_id = c29.id)
    uc30 = UserCat(user_id = u2.id, cat_id = c30.id)
    uc31 = UserCat(user_id = u2.id, cat_id = c31.id)
    uc32 = UserCat(user_id = u2.id, cat_id = c32.id)
    uc33 = UserCat(user_id = u2.id, cat_id = c33.id)
    uc34 = UserCat(user_id = u2.id, cat_id = c34.id)
    uc35 = UserCat(user_id = u2.id, cat_id = c35.id)
    uc36 = UserCat(user_id = u2.id, cat_id = c36.id)
    uc37 = UserCat(user_id = u2.id, cat_id = c37.id)
    uc38 = UserCat(user_id = u2.id, cat_id = c38.id)
    uc39 = UserCat(user_id = u2.id, cat_id = c39.id)
    uc40 = UserCat(user_id = u2.id, cat_id = c40.id)
    uc41 = UserCat(user_id = u2.id, cat_id = c41.id)
    uc42 = UserCat(user_id = u2.id, cat_id = c42.id)
    uc43 = UserCat(user_id = u2.id, cat_id = c43.id)
    uc44 = UserCat(user_id = u2.id, cat_id = c44.id)
    uc45 = UserCat(user_id = u2.id, cat_id = c45.id)
    uc46 = UserCat(user_id = u2.id, cat_id = c46.id)
    uc47 = UserCat(user_id = u2.id, cat_id = c47.id)
    uc48 = UserCat(user_id = u2.id, cat_id = c48.id)
    uc49 = UserCat(user_id = u2.id, cat_id = c49.id)
    uc50 = UserCat(user_id = u2.id, cat_id = c50.id)

    usercats = [uc1, uc2, uc3, uc4, uc5, uc6, uc7, uc8, uc9, uc10, uc11, uc12, uc13, uc14, uc15, uc16, uc17, uc18, uc19, uc20, uc21, uc22, uc23, uc24, uc25, uc26, uc27, uc28, uc29, uc30, uc31, uc32, uc33, uc34, uc35, uc36, uc37, uc38, uc39, uc40, uc41, uc42, uc43, uc44, uc45, uc46, uc47, uc48, uc49, uc50]
    db.session.add_all(usercats)
    db.session.commit()



    print("seeding done")